import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar";
import styles from '@/app/page.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.html}>
      <body className={`${inter.className} ${styles.body}`} id={styles.body}>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
